config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user, :optional => true
    belongs_to :category
    belongs_to :genre
    belongs_to :game
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :articles
    belongs_to :genre
end

app/models/game.rb
class Game < ActiveRecord::Base
    has_many :articles
end

app/models/genre.rb
class Genre < ActiveRecord::Base
    has_many :articles
    has_many :categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_validation :authenticate_user!
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  protect_from_forgery with: :exception
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /articles
  # GET /articles.json
  def index
    if params[:category].blank?
      @articles = Article.all
    else
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(category_id: @category_id)
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :image_url, :category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, class: 'form-control', placeholder: 'Enter the title' %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, class: 'form-control', placeholder: 'Enter the description' %>
  </div>

  <div class="form-group">
    <%= form.text_field :image_url, class: 'form-control', placeholder: 'Enter the image url' %>
  </div>

  <div class='c-select'>
    <%= form.collection_select :category_id, Category.all, :id, :name, {prompt: 'Choose a Weapon Category'}, class: 'form-control' %>
  </div>

  <div class='c-select'>
    <%= form.collection_select :category_id, Genre.all, :id, :name, {prompt: 'Choose a Weapon Genre'}, class: 'form-control' %>
  </div>
  
  <div class='c-select'>
    <%= form.collection_select :category_id, Game.all, :id, :name, {prompt: 'Choose a Game Title'}, class: 'form-control' %>
  </div>
  
  
  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-default btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<% if request.original_url.split('=').last.include? '/' %>
<h1>All Articles</h1>
<% else %>
<h1>All <%= request.original_url.split('=').last %> Articles </h1>
<% end %>


<div class='jumbotron'>
  <%= @articles.each do |article| %>
  <h2>
    <%= article.title %>
  <h2>
  <h5>
    <%= link_to 'Read More', article_path(article) %>
  </h5>
  <h5>
    <%= truncate(article.body, length: 200) %>
  </h5>
  <% end %>
</div>


    
  

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class='jumbotron'>
  <p id="notice"><%= notice %></p>
  <div class='row'>
    <div class='col-lg-7'>
      <h1>
        <%= @article.title %>
      </h1>
      <p>
        <%= @article.body %>
      </p>
    </div>
    <div class='col-lg-2'>
      <%= image_tag @article.image_url, :alt => @article.title, float: 'right' %>
    </div>
  </div>

  

  <% if user_signed_in? %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
  <% end %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoulsBourneWiki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">SoulsBourneWiki</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>

      <% if user_signed_in? %>

        <li class="nav-item">
          <a class='nav-link' href='<%= new_article_path %>'>New Article</a>
        </li>
        <li class="nav-item">
          <a class='nav-link' href='<%= destroy_user_session_path %>'>Sign Out</a>
        </li>

      <% else %>

        <li class="nav-item">
          <a class='nav-link' href='<%= new_user_registration_path %>'>Sign Up</a>
        </li>
        <li class="nav-item">
          <a class='nav-link' href='<%= new_user_session_path %>'>Sign In</a>
        </li>

      <% end %>

    </ul>
  </div>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      
      <li class='nav-item'>
        Logged in as '"00\\||//00"'
      </li>
      
    </div>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class='container'>
  <div class='row'>
    <div class='col-lg-10'>

      <%= yield %>

    </div>
    <div class='col-lg-2'>
      <ul class='nav nav-pills flex-column'>
        <li class='nav-item'><%= link_to 'All Weapons', root_path, class: 'nav-link' %></li>

        <% Genre.all.each do |genre| %>

        <li class='nav-item dropdown'>
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="<%= articles_path(genre: genre.name) %>" 
            role="button" aria-haspopup="true" aria-expanded="false">
            <%= genre.name %>
          </a>
        
          <% Category.all.each do |category| %>

          <div class="dropdown-menu">
            <a class="dropdown-item" href="<%= articles_path(category: category.name) %>">
              <%= category.name %>
            </a>
          </div>

          <% end %>
        <% end %>
        
        </li>
    </div>
  </div>




  </body>
</html>